---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 36.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    nextcloud:
      php:
        memory_limit: 3G
        upload_limit: 30G
        pm_max_children: 540
        pm_start_servers: 54
        pm_min_spare_servers: 36
        pm_max_spare_servers: 90
      credentials:
        initialAdminUser: admin
        initialAdminPassword: adminpass
      general:
        default_phone_region: IT
        #accessIP: ${NGINX_EXTERNAL_IP}
        accessIP: ${NGINX_INTERNAL_IP}
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          #- host: "nextcloud.${DOMAIN_0}"
          #  paths:
          #    - path: /
          - host: nextcloud.cloud.local
            paths:
              - path: /
        tls:
          - hosts:
            #  - "nextcloud.${DOMAIN_0}"
              - nextcloud.cloud.local
        integrations:
          traefik:
            enabled: false
#    credentials:
#      s3:
#        type: s3
#        url: "${S3_ENDPOINT}"
#        bucket: "${S3_BUCKET}"
#        accessKey: "${S3_ID}"
#        secretKey: "${S3_KEY}"
#        encrKey: "${S3_KEY}"
    persistence:
#      html:
#        volsync:
#          - name: html
#            type: restic
#            credentials: s3
#            dest:
#            src:
#             enabled: true
#              enabled: true
#      config:
#        volsync:
#          - name: config
#            type: restic
#            credentials: s3
#            dest:
#             enabled: true
#            src:
#              enabled: true
      data:
        type: nfs 
        path: /mnt/NASCasa/nextcloud
        server: "192.168.1.123"
        targetSelector:
          main:
            main:
              mountPath: /var/www/html/data
            init-perms:
              mountPath: /var/www/html/data
          nextcloud-cron:
            nextcloud-cron:
              mountPath: /var/www/html/data
          preview-cron:
            preview-cron:
              mountPath: /var/www/html/data
          nginx:
            nginx:
              mountPath: /var/www/html/data
              readOnly: true
    
#    cnpg:
#      main:
#        backups:
#          enabled: true
#          credentials: s3
#        recovery:
#          credentials: s3
