---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: icloudpd
  namespace: icloudpd
spec:
  interval: 15m
  chart:
    spec:
      chart: icloudpd
      version: 9.3.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    icloudpd:
      apple_id: "${APPLE_ID}"
    persistence:
      data:
        type: nfs 
        path: /mnt/NASCasa/icloudpd
        server: "192.168.1.123"